services:
  # PostgreSQL
  postgres-db:
    image: postgres:15-alpine
    container_name: taskflow-postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - taskflow-network

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:4-management
    container_name: taskflow-rabbitmq
    restart: always
    ports:
      - "5672:5672" # port for NestJS
      - "15672:15672" # port for webbrowser
    environment:
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_USER?Error: no RABBITMQ_USER in .env}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_PASSWORD?Error: no RABBITMQ_PASSWORD in .env}"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - taskflow-network

  # NestJS backend API
  backend-api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: taskflow-backend
    restart: always
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      PORT: ${BACKEND_PORT}
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      RABBITMQ_URL: "amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbitmq:5672"
    depends_on:
      - postgres-db
      - rabbitmq
    networks:
      - taskflow-network

  # Next.js Frontend
  frontend-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: taskflow-frontend
    restart: always
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    environment:
      PORT: ${FRONTEND_PORT}
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    depends_on:
      - backend-api
    networks:
      - taskflow-network

volumes:
  postgres_data:
  rabbitmq_data:

networks:
  taskflow-network:
    driver: bridge
